triangle: glfw_triangle.c
	gcc -Wall -g glfw_triangle.c -lglfw -lGLESv2 -lm

gears: gears.c 
	gcc -Wall -g -I. -o gears gears.c -lglfw -lGLESv2 -lm

glfw_test: glfw_test.c
	gcc -Wall -Wpedantic -g -I . -o glfwtest glfw_test.c -lglfw -lGLESv2 -lm

